spring.application.name=gestao-competencias
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
spring.sql.init.mode=never
server.port=8005

spring.autoconfigure.exclude[0]= org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
