spring.application.name=gestao-competencias
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
spring.sql.init.mode=never
server.port=8005

#JWT
auth.jwt-secret=AMinhaSenh$eDificilPraCaramba4#2025@SistemaGest40
auth.jwt-expiration-miliseg=1200000
