spring.datasource.url=jdbc:postgresql://localhost:5432/gestao
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=false
spring.sql.init.mode=never